Logging
YuraHrysyuk/API-Health-Monitor pull request #9
Opened 2020-07-23 16:55 UTC by Eshmann

Logging flow implemented it in .NET Core app

2020-07-23 17:14 UTC, Sergiy-Dev approved these changes

2020-07-23 17:41 UTC, YuraHrysyuk commented on APIHealthMonitorApplication/APIHealthMonitorApplication.csproj
> +
Please remove this line

2020-07-23 17:41 UTC, YuraHrysyuk commented on APIHealthMonitorApplication/Controllers/ErrorController.cs
> +}
Do we really need this one?

2020-07-23 17:41 UTC, YuraHrysyuk commented on APIHealthMonitorApplication/Logs/Log-20200723.txt
> +   at APIHealthMonitorApplication.Middleware.CustomExceptionMiddleware.InvokeAsync(HttpContext httpContext) in C:\Users\mitek\Downloads\API-Health-Monitor\API-Health-Monitor\APIHealthMonitorApplicati
Please add this file to ignore list since it must be generated for each developer separately once error appeared and no Log file year

2020-07-23 17:41 UTC, YuraHrysyuk commented on APIHealthMonitorApplication/Middleware/CustomExceptionMiddleware.cs
> +
Please remove redundant lines

2020-07-24 15:50 UTC, YuraHrysyuk requested changes

2020-07-24 15:50 UTC, YuraHrysyuk commented on APIHealthMonitorApplication/Controllers/WeatherForecastController.cs
> +        }
Looks like we do not need this method for tests, please remvoe it.

2020-07-24 15:50 UTC, YuraHrysyuk commented on APIHealthMonitorApplication/Logs/Log-20200723.txt
> +   at APIHealthMonitorApplication.Middleware.CustomExceptionMiddleware.InvokeAsync(HttpContext httpContext) in C:\Users\mitek\Downloads\API-Health-Monitor\API-Health-Monitor\APIHealthMonitorApplicati
Please remove this file from changes

2020-07-24 15:50 UTC, YuraHrysyuk commented on APIHealthMonitorApplication/Program.cs
> +
Please remove empty lines :)

2020-07-24 20:20 UTC, YuraHrysyuk approved these changes

2020-07-24 22:09 UTC, merged